[package]
name = "sekhmet-server"
version = "0.1.0"
authors = ["Sean Klein <seanmarionklein@gmail.com>"]

[dependencies]
chrono = "*"
google-calendar3 = "*"
google-fitness1 = "*"
hyper = "0.10.13"
hyper-rustls = "0.6"
time = "*"
sysfs_gpio = "*"
yup-oauth2 = "*"
